### ISSUE TITLE
PureEntitiesX -> Shop problem

### ISSUE THREAD

**Issue by benda95280** [thebigsmileXD/BedWars#17]
Hello,

If we use PureEntitiesX with Bedwarz, the villager jump and sometimes disapear.
Shop cannot be open too.

Could you solve this issue ?
(No problem with villager spawned with slapper)

Could i use slapper to open Shop ? Which command should i use ?

**Comment by thebigsmileXD** [comment]
The villager is just a normal villager, thats why pureentitiesx removes it.
I highly suggest to not run bedwars and pureentitiesx on the same server, it might also create other issues, i.e. opening shops or similar.
---
Solution i consider to use: i might add a custom villager entity. But this was intentionally not done, because i wanted villagers from imported worlds to function directly / by default.

**Comment by benda95280** [comment]
I've been able to do it work with Slapper, the solution is not really nice.

Edit EventListener.php:
Add on top: **use slapper\entities\SlapperHuman;**

Add after the **IF**:
 **if ($event->getEntity() instanceof Villager) {**

> 						if ($event->getEntity() instanceof SlapperHuman) {
>                             if (($arena = API::getArenaByLevel(Loader::getInstance(), $event->getEntity()->getLevel())) instanceof Arena) {
>                                 if ($arena->getState() !== Arena::INGAME /*&& $arena->getState() !== Arena::SETUP*/) {
> 									Loader::getInstance()->getServer()->getLogger()->info(TextFormat::BLUE."BW: Access to shop not ingame !");
>                                     $event->setCancelled();
>                                     return;
>                                 }
>                                 Loader::getInstance()->openShop($damager);
>                             }
> 						}
>

**Comment by thebigsmileXD** [comment]
I will NOT add code from other plugins into this plugin.
Firstly because of compatibility issues, secondly this is hacky
