### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by jsnfjsfjbwiea** [thebigsmileXD/BedWars#45]
_Item purchasing does not seem to work for me on Windows 10 edition, but it works on my phone fine [GOT IT TO WORK]._ **Also the map isnt getting rid of the blocks once the match is over, is there a game timer option we can set?.**

Some suggestions;

Boss bar at the time showing how much game time is left

Announcements in chat when a bed is destroyed

Winner/team alerts, announces which team wins

A custom shop, not the default one given.

Perhaps a custom score hud, showing which beds are alive, or broken

Changing currency; for example,
bricks become iron
iron become diamonds
and gold becomes emeralds
to make it more bedwar like

Messages of when the next gold piece will spawn, maybe a counter above the spawners like The Hive

**Comment by thebigsmileXD** [comment]
> Also the map isnt getting rid of the blocks once the match is over,
The whole level folder is restored from a folder backup that is created upon /bw endsetup. Make sure you used the commands correctly.
> Item purchasing does not seem to work for me on Windows 10 edition
This might be a 1.14 issue, i will investigate
> Boss bar at the time showing how much game time is left
There purposely is no game timer. See TODO's
> Announcements in chat when a bed is destroyed
It is announced as title (and as far as i know even in chat)
> Winner/team alerts, announces which team wins
They are announced by title. Get gamerewards for further customisation
> A custom shop, not the default one given.
This is planned, see TODO's
> Perhaps a custom score hud, showing which beds are alive, or broken
I am repeating myself. This is planned, see TODO's
> Changing currency; for example,
This is based on the idea of MCJava OG BedWars, where Bronze, Silver, and Gold are used. Probably no.
> Messages of when the next gold piece will spawn, maybe a counter above the spawners like The Hive
This causes extra lag and struggle on the game due to the fact that how drop timers are implemented. I will not rip off features from The Hive, i don't want to get any legal issue.
Planned though is stacking the items, and showing the count as name tag above the item. You can see that on salmonde's server.

I will close this issue since first, it is packed with too many "issues" at once, and secondly, i will tag this "invalid", since most of the stuff said above is already represented in the TODO list in the readme.
